### ISSUE TITLE
Plotting large raster object

### ISSUE THREAD

**Issue by gdkrmr** [r-tmap/tmap#578]
Plotting a large raster object:
```
class       : SpatRaster 
dimensions  : 225, 175, 1  (nrow, ncol, nlyr)
resolution  : 4000, 4000  (x, y)
extent      : 4038000, 4738000, 5220000, 6120000  (xmin, xmax, ymin, ymax)
coord. ref. : +proj=tmerc +lat_0=0 +lon_0=12 +k=1 +x_0=4500000 +y_0=0 +ellps=bessel +towgs84=598.1,73.7,418.2,0.202,0.045,-2.455,6.7 +units=m +no_defs 
source      : GDM_SWC_5_25cm_1951-2015_inv_compr.nc 
varname     : SWC_L02 (soil water content of soil layer         2) 
name        : SWC_L02_1 
time        : 1951-01-01 23:00:00 
```
just fills up memory. What is happening here? Just using `plot` works fine.

The underlying file is a NetCDF file that is ~4GB large

**Comment by mtennekes** [comment]
Where can I find this file?

**Comment by gdkrmr** [comment]
Sorry, it is not publicly available. I could upload it somewhere and share a private link if you want it for debugging.

**Comment by mtennekes** [comment]
That would be great! Otherwise, it is also sufficient to know where I can download an nc file of similar size.

I already know what the problem is: `terra` objects are converted to `stars`, which take time and memory. Ideally, converting  `terra` objects with a pointer to a large source file is done by creating a `stars` object from scratch with pointing to the same source file and with the same other properties (such as resolution and crs).

In the meantime, you can try to read the object with `stars::read_st`, which should work (fast and memory efficient).

**Comment by gdkrmr** [comment]
You should have gotten an Email. 
```
guf2 <- stars::read_stars("data/GDM_SWC_5_25cm_1951-2015_inv_compr_sachsen.nc")

guf2 %>%
  slice(time, 1) %>%
  plot()

guf2 %>%
  slice(time, 1) %>%
  tm_shape() +
  tm_raster()

```
Both work fine. I get the same memory leak if I don't `slice` the data first.

**Comment by mtennekes** [comment]
The `plot` method also doesn't work without `slice`. The problem is that there is a huge number of time slices:

```r
stars::st_dimensions(guf2)
     from    to                  offset  delta  refsys point values x/y
x       1    55                 4490000   4000      NA    NA   NULL [x]
y       1    43                 5732000  -4000      NA    NA   NULL [y]
time    1 23741 1951-01-01 23:00:00 UTC 1 days POSIXct    NA   NULL    
```

I assume you don't want to plot 23741 facets?

`tmap` uses `stars::st_downsample` for `stars` objects with a large number of raster cells. This dataset has not many cells (55*43) but many layers. Perhaps it would be good to slice the stars object automatically when there are more layers than allowed number of facets (see `tmap_options("limits")`).

**Comment by mtennekes** [comment]
It's working now. Stars with many layers in the 'other' dimension are sliced to the maximum number of facets (see `tmap_options("limits")`).

Note that this example doesn't work *yet* for terra objeects, because of a small bug in `sf` for which I made a PR (https://github.com/r-spatial/sf/pull/1739)
