### ISSUE TITLE
Specifying a midpoint in a custom palette

### ISSUE THREAD

**Issue by ailich** [r-tmap/tmap#600]
How would you go about specifying a midpoint in a custom palette? With the default palette, midpoint will shift the color scale (e.g. yellow moves from 0 to 3 in example), but in my custom palette which should have gray in the center, the midpoint argument does not affect the color scale.

```
library(raster)
library(tmap)

set.seed(5)
r<- raster(matrix(data=runif(1000, min = -2, max=5), nrow=100, ncol=100))

tm_shape(r)+
  tm_raster(style = "cont", legend.reverse = TRUE, midpoint = 0, breaks = c(-2,-1,0,1,2,3,4,5))+
  tm_layout(legend.outside = TRUE, aes.palette = "div", main.title= "Default Pal, Diverge 0")

```
![d0](https://user-images.githubusercontent.com/28163862/133686827-7ae07ccb-0e34-46f6-830d-329950c15000.png)

```
tm_shape(r)+
  tm_raster(style = "cont", legend.reverse = TRUE, midpoint = 3, breaks = c(-2,-1,0,1,2,3,4,5))+
  tm_layout(legend.outside = TRUE, aes.palette = "div", main.title= "Default Pal, Diverge 3")
```

![d3](https://user-images.githubusercontent.com/28163862/133686957-084da319-a9a5-4eff-a89e-4c77e5ee6091.png)

```
custom_pal<- colorRampPalette(c("blue", "gray", "red"))(100)
# Midpoint should be grey in color
barplot(1, col=custom_pal[50], axes=FALSE)
```
![mid_col](https://user-images.githubusercontent.com/28163862/133687052-27349560-0ed3-439a-a4bb-f1e3f827c4e3.png)

```
# Gray does not match up with specified midpoint value, and plots do not change when midpoint argument is changed
tm_shape(r)+
  tm_raster(palette = custom_pal, style = "cont", legend.reverse = TRUE, midpoint = 0, breaks = c(-2,-1,0,1,2,3,4,5))+
  tm_layout(legend.outside = TRUE, aes.palette = "div", main.title= "Custom Pal, Diverge 0")
```
![C0](https://user-images.githubusercontent.com/28163862/133687226-4a746442-fc40-4f39-9ce8-086661376e96.png)

```
tm_shape(r)+
  tm_raster(palette = custom_pal, style = "cont", legend.reverse = TRUE, midpoint = 3, breaks = c(-2,-1,0,1,2,3,4,5))+
  tm_layout(legend.outside = TRUE, aes.palette = "div", main.title= "Custom Pal, Diverge 3")
```
![C3](https://user-images.githubusercontent.com/28163862/133687258-063fe4ec-5e6a-495e-8651-5c8e7f37a0bd.png)

**Comment by mtennekes** [comment]
This is an ugly artifact of the current implementation: when the manual palette is exactly the same length as the number of color classes, then it is assumed that the user wants to use the palette literally, so the midpoint is ignored.
This makes sense for class intervals, but not for continuous color scales. However under the hood tmap uses 100 classes for the continuous scale, exactly the length of your `custom_pal`.

Easy fix:

``` r
library(raster)
library(tmap)
set.seed(5)
r<- raster(matrix(data=runif(1000, min = -2, max=5), nrow=100, ncol=100))

custom_pal<- c("blue", "gray", "red")

tm_shape(r)+
    tm_raster(palette = custom_pal, style = "cont", legend.reverse = TRUE, midpoint = 0, breaks = c(-2,-1,0,1,2,3,4,5))+
    tm_layout(legend.outside = TRUE, aes.palette = "div", main.title= "Custom Pal, Diverge 0")
#> Warning: Currect projection of shape r unknown. Long lat (epsg 4326) coordinates
#> assumed.
```

![](https://i.imgur.com/SgvyGQS.png)

<sup>Created on 2021-09-17 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

So you don't need the `colorRampPalette`, because this is already done in tmap.

I will not fix this artifact in tmap3, but will make sure it works well in tmap4.

**Comment by ailich** [comment]
Awesome, thanks!
