### ISSUE TITLE
The legend ticks of tmap V4 does not work in tm_raster( ) 

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#702]
Dear Nowosad, 
The legend ticks of tmap V4 work in tm_polygons function, but does not work in tm_raster( ) function.

``` r
# remotes::install_github("r-tmap/tmap@v4")
library(tmap)
data(land, World)

tm_shape(land) +
  tm_raster("elevation", col.scale = tm_scale_continuous(values = terrain.colors(9))) +
  tm_shape(World) +
  tm_borders()
```

![](https://i.imgur.com/uDmWtJP.png)

``` r

# compare legends side by side
tm_shape(land) +
  tm_raster("elevation", col.scale = tm_scale_continuous(values = terrain.colors(9))) +
  tm_shape(World) +
  tm_polygons("life_exp", fill.scale = tm_scale_continuous(values = terrain.colors(9)))
```

![](https://i.imgur.com/ZFDVJfO.png)

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

_Originally posted by @Yelong-Z in https://github.com/r-tmap/tmap/issues/508#issuecomment-1437856606_

**Comment by mtennekes** [comment]
ticks now have the same color as the text (rather than the frame around the colors)

Speaking of which: currently, the frame around the colors resembles how colors are used in the map. E.g.:

``` r
library(tmap)
#> 
#> Attaching package: 'tmap'
#> The following object is masked from 'package:datasets':
#> 
#>     rivers
tm_shape(World) + tm_polygons(fill = "HPI", col = "red")
```

![](https://i.imgur.com/1SXjNLD.png)

``` r
tm_shape(World) + tm_polygons(fill = "HPI", col = NA)
```

![](https://i.imgur.com/YT7OCv5.png)

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

The same applies to continuous legends:

``` r
library(tmap)
#> 
#> Attaching package: 'tmap'
#> The following object is masked from 'package:datasets':
#> 
#>     rivers
tm_shape(World) + tm_polygons(fill = "HPI", col = "red", fill.scale = tm_scale_continuous())
#> Warning: Some legend items do not fit with the specified font size, and
#> therefore were rescaled.
```

![](https://i.imgur.com/9rQxlTh.png)

``` r
tm_shape(World) + tm_polygons(fill = "HPI", col = NA, fill.scale = tm_scale_continuous())
#> Warning: Some legend items do not fit with the specified font size, and
#> therefore were rescaled.
```

![](https://i.imgur.com/3r334uM.png)

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>


Is that clear and intuitive for the user? Ideally, the user should be able to adjust this.

**Comment by Nowosad** [comment]
@mtennekes this is an interesting idea -- I do not know yet what to think about it. I would probably need to see it in action (on my data/problems) a few times before making my mind. At the same time, I agree that ideally the user should be able to adjust this.

**Comment by Robinlovelace** [comment]
> Is that clear and intuitive for the user? Ideally, the user should be able to adjust this.

Not intuitive. The colour of the frames around the legend items should not be determined by `col` IMO. Agree the user should be able to adjust it but black or no colour would be my preference.

**Comment by mtennekes** [comment]
Thanks for your feedback @Robinlovelace! In some cases it makes sense to let the legend items border be determined by the `col` imo because the spatial feature are better represented. For instance

![68747470733a2f2f692e696d6775722e636f6d2f3153586a4e4c442e706e67](https://user-images.githubusercontent.com/2444081/221305049-2d96486e-610e-4b71-bed7-702d9b216793.png)

will look off/wrong with black borders. Another (better) example:

```{r}
tm_shape(World) +
  tm_symbols(size = "pop_est",
    col = "purple", lwd = 2, 
    size.scale = tm_scale_continuous(values.scale = 2))
```

![image](https://user-images.githubusercontent.com/2444081/221306350-fc1db0fd-b283-4873-9265-67caafa4d72d.png)

Note that such examples (with colourful borders) are rare. Normally, a grayscale color (black or dark grey) is used. Then it is not an issue.

For the gradient legends, this argument is weaker, so for that case, I am open to change it. But which color? (Keeping in mind other styles, which can be dark-themes). Two options come to mind: the color of the legend frame, or the color of the text and ticks.

**Comment by Robinlovelace** [comment]
I see your point Martijn, many thanks for the reprexes. Another argument, e.g. `col.legend.border`?
