### ISSUE TITLE
No popups in v4? & git issues

### ISSUE THREAD

**Issue by Robinlovelace** [r-tmap/tmap#764]
I've just tried the following:

```r
tm_shape(opengeo_sf) +
  tm_symbols(popup.vars = "name")
```

In interactive mode. Source where I've tried this: https://github.com/Robinlovelace/opengeohub2023/blob/main/tidy.qmd

**Comment by Robinlovelace** [comment]
The plot work, but no pop-ups when I click. Also could not figure our how to get markers, plus `tm_bubbles()` has gone (may be a good decision)!

**Comment by Robinlovelace** [comment]
- What could be improved from user perspective?
    - The package already has a great API. It could be made more intuitive and have slightly better defaults in some ways, but I think that can be done after feature-completeness, and things not being intuitive can be greatly mitigated by having good docs and a strong user community, which will coalesce after v4 is out I think, you'll get lots of suggestions I'm sure after v4 is on GitHub and I suggest doing a social media call-to-arms for people to suggest what could be made more intuitive during this window of opportunity where breaking changes have low costs (although pushing v4 to CRAN soon and making a few more breaking changes until v4.1 or maybe even v4.2 or v4.3 will be fine IMO, go fast break things being my thinking)!
 
- #749 was a pain for sure, no other bit issues jump to mind.

No strong feelings about `tm_bubbles()`. If easy to re-implement the pros may outweigh the cons, totally fine as a function.

**Comment by mtennekes** [comment]
What is the most intuitive API for mouse-click popups and mouse-over labels?

In v3 we have three arguments per layer function:

* `popup.vars`
* `popup.format`
* `id`

When `popup.vars==TRUE`, all variables are shown in the popup, when not specified (`NA`), only the visual variables are shown, and when `FALSE` it is disabled.

Imo, this is ok and rather intuitive, but I'm open to suggestions.

The  `id` is confusing, because it serves 3 purposes at once: 1) as mouse-over label, 2) as bold header in the popups, and 3) as `layerId` specification (e.g. in `leaflet::addPolygons`). The last one could be useful to Shiny integration, or further javascript add-ons, where 


One improvement I thought about to reduce the number of layer-function-arguments: stick with one argument for popups, in which variables, titles, and label format can be specified. E.g. `popup = tm_popups(vars = c("pop_est_dens", "economy"), header = "name")`

And similarly, one argument for hover label, e.g. `label = "iso_a3"`. I think we does need something like  `tm_hover` because afaik only the hover label has to be defined.

Perhaps another argument for the layer id called `"id"`, just for layerId specification?

**Comment by Robinlovelace** [comment]
> When `popup.vars==TRUE`, all variables are shown in the popup, when not specified (`NA`), only the visual variables are shown, and when `FALSE` it is disabled.

Agreed, this is perfect.

**Comment by Robinlovelace** [comment]
> Perhaps another argument for the layer id called `"id"`, just for layerId specification?

Sounds reasonable, no strong feelings or comments at this stage from me. Many thanks for thinking about these options and for working on it. The sooner that the v4 branch is merged the better IMO.

**Comment by mtennekes** [comment]
Ok, for now I'll settle with the easiest option: `popup.vars`, `popup.format`, `label` and `id`. So `label` will be used  for the hovering label (default will be `""` as suggested  #749).

When do you think is a good time to merge v4 to master? Imo we can do this now (well, maybe after I've finish this issue;-))

I'm planning to submit v3 to CRAN soon, the latest minor update (will be 3.3-4). Thinking about a startup-message about v4 coming up. Not all users will be active on GitHub or social media.

**Comment by Nowosad** [comment]
I think: merge v4 immediately after a new v3 is on CRAN. Small startup message should be fine.

**Comment by Robinlovelace** [comment]
Great work, thanks Martijn!

**Comment by mtennekes** [comment]
> I think: merge v4 immediately after a new v3 is on CRAN. Small startup message should be fine.

Done! tmap 3.3-4 is ready to be submitted, but I'll do that next week.

**Comment by mtennekes** [comment]
@Robinlovelace and @Nowosad 

tmap 3.3-4 is submitted :-)

I've created a branch called "v3" successfully


And I've merged v4 into the master branch. However, not 100% sure if all went well. First I did a `git merge v4`, but had many merging conflicts (probably because of the changes to the master since v4 was created). So I followed this strategy https://stackoverflow.com/questions/2862590/how-to-replace-master-branch-in-git-entirely-from-another-branch

It seems ok, but when I go to v4 again I see "This branch is 85 commits behind master"

Could you please check?

**Comment by Nowosad** [comment]
@mtennekes it installs ok, and the geocompr book can be compiled using this version
