### ISSUE TITLE
tm_rgb not recognizing arguments

### ISSUE THREAD

**Issue by r-poloni** [r-tmap/tmap#781]
Hi, sorry is this is a misunderstanding of the manual, but I cannot figure out what is going on.
I am using the github version 4 of tmap and I provide a partially reproducible example.
`
library(tmap)
library(tmaptools)
library(spData)
library(stars)

ext <- read_sf("extshp")
class(ext)
#[1] "sf"         "tbl_df"     "tbl"        "data.frame"
elev.file <- system.file("raster/elev.tif", package = "spData")
elev <- read_stars(elev.file)
tm_shape(elev) +
  tm_raster(elev.file, palette = "viridis") +
  tm_shape(ext)+
  tm_borders()

`
This results in: 
Error in tm_raster(elev.file, palette = "viridis") : 
  unused argument (palette = "viridis")

Another error, very similar:

`
terrain <- read_stars("local_stamen_terrain_file.tif")
tm_shape(terrain) +
  tm_rgb(r=1, g=2, b=3) +
  tm_shape(ext)+
  tm_borders()+

`
This results in this error:
Error in tm_rgb(r = 2, g = 1, b = 3) : 
  unused arguments (r = 2, g = 1, b = 3)

However, it exactly the same code that is used here: https://r-tmap.github.io/tmap-book/layers.html and 4 days ago worked perfectly. I really cannto figure out what's going on. It seems that tm_map does not accept any more the arguments I gave.

**Comment by mtennekes** [comment]
The first example is a typo in your code, as well as a not-yet-backwards compatible issue in tmap4, which is easy to solve.

Your typo:

```r
elev.file <- system.file("raster/elev.tif", package = "spData")
elev <- read_stars(elev.file)
tm_shape(elev) +
tm_raster(elev.file, palette = "viridis") +
tm_shape(ext)+
tm_borders()
```

should be

```r
elev.file <- system.file("raster/elev.tif", package = "spData")
elev <- read_stars(elev.file)
tm_shape(elev) +
tm_raster("elev.tif", palette = "viridis") +
tm_shape(ext)+
tm_borders()
```

The `palette` argument is v3, but should be backwards compatible with v4. In v4:

```r
tm_shape(elev) +
	tm_raster("elev.tif", col.scale = tm_scale(values = "viridis"))
```

I don't have "local_stamen_terrain_file.tif", but in v4 it should be something like this:

```
terrain <- read_stars("local_stamen_terrain_file.tif")
tm_shape(terrain) +
tm_rgb(tm_mv(1, 2, 3))
```

Please share this file in order to reproduce it.

**Comment by mtennekes** [comment]
Documentation is still lagging, but here is the explanation:

The `landsat` does not contain multiple variables as  "attributes" in stars terms), but inside a new "dimension" in stars terms.

For that there will be a special function, called `tm_mv_dim`:

```r
tm_shape(landsat) + tm_rgb(tm_mv_dim("band", c(4,3,2)), col.scale = tm_scale_rgb(maxValue = 32768))
```

These dimensions can be split by attributions manually:

```r
landsat2 = terra::rast(landsat)
tm_shape(landsat2) + tm_rgb(tm_mv(c("X4", "X3", "X2")), col.scale = tm_scale_rgb(maxValue = 32768))
```

The attributes view (rather than the extra-dimension view) is also used by terra:

```r
landsat_terra = terra::rast(landsat)
tm_shape(landsat_terra) + tm_rgb(tm_mv(c("band4", "band3", "band2")), col.scale = tm_scale_rgb(maxValue = 32768))
```

**Comment by r-poloni** [comment]
Hi! Thank you, this works fine. Great!
This problem, anyway, is not only for landsat, but for all custon rasters I guess, and read with stars which I thought was the suggested package. I am looking forwrd to see the new function!

**Comment by mtennekes** [comment]
You're welcome.

terra and stars are both awesome, but generally speaking terra is a bit user friendlier whereas stars can do more (irregular grids, data cubes, etc.)
