### ISSUE TITLE
tmap_v4 can't project `stars` object properly

### ISSUE THREAD

**Issue by evanliu3594** [r-tmap/tmap#789]
```
> data(land)
> tm_shape(land, crs = "+proj=robin") + tm_raster("elevation")
Error: Unable to warp stars. You could try with raster.warp = FALSE (argument of tm_shape)
> tm_shape(land, crs = "+proj=robin", raster.warp = FALSE) + tm_raster("elevation")
Error: Unable to warp stars. You could try with raster.warp = FALSE (argument of tm_shape)
```

**Comment by mtennekes** [comment]
Fixed now.

I've removed the argument `raster.warp` from v4, because it is not useful. Now the first strategy is warp (`st_warp`) and if unsuccessful, then throw a warning and try a (slow) transformation (`st_transform`).

Somehow, the warp won't work with `"robin"`. However, with `crs = "+proj=eck4"` is does work.
