### ISSUE TITLE
In mode = "view", could tm_credits use `leaflet::addTiles()`

### ISSUE THREAD

**Issue by olivroy** [r-tmap/tmap#806]
I sometimes use (in v3)

```r
library(tmap) # tmap v3.3.4
data(World, package = "tmap")
tmap_mode("view")
my_map <- tm_shape(World) +
  tm_polygons(title = "the title of my map", col = "area") +
  tm_basemap("OpenStreetMap") + tm_layout("title of my map") 

my_map

my_map |> 
  tmap_leaflet() |> 
  leaflet::addTiles(attributions = "Last update in October 2023")
```

Could this be equivalent as 

```r
my_map <- tm_shape(World) +
  tm_polygons(title = "the title of my map", col = "area") +
  tm_basemap("OpenStreetMap") + tm_layout("title of my map")  +
  tm_credits("Last update in October 2023")
```

Thanks

Apologies if this already exists in v4. I just wanted to type it quickly.

**Comment by mtennekes** [comment]
Good point, this should be done in v4.

In R-leaflet, the attributions are collected via the `addTiles` and `addWMSTiles` calls, and are placed in the HTML as follows:

```html
<div class="leaflet-bottom leaflet-right">
  <div class="leaflet-control-attribution leaflet-control">
    <a href="https://leafletjs.com" title="A JS library for interactive maps">Leaflet</a> | Attribution A | Attribution B
  </div>
</div>
```

So in tmap we could collect all the tm_credits text, concatenate to `credits_text`, and pass it on via a dummy tile layer:

```r
addTiles(urlTemplate = "", attribution = credits_text)
```

However, ideally, I would like to have more control of this attribution text via a function like `addAttribution` or `setAttribution`. @tim-salabim do you know if a function like this exists somewhere?

**Comment by mtennekes** [comment]
Implemented, but I'd like your opinions about the defaults @olivroy and @Nowosad 

Without `tm_credits`, the original attribution text appears (depends on the used tile layers):

```r
tm_shape(world) + tm_polygons()
```

![image](https://github.com/r-tmap/tmap/assets/2444081/b6c04704-3ca2-4bdf-9ffc-4d7b03cd2279)

With `tm_credits` defined, the attribution text is replaced with the specified text:

```r
tm_shape(world) + tm_polygons() + tm_credits("My attribution text")
```

![image](https://github.com/r-tmap/tmap/assets/2444081/39add002-93d0-4392-9ce8-34170dcac23d)

Without arguments:

```r
tm_shape(world) + tm_polygons() + tm_credits()
```


![image](https://github.com/r-tmap/tmap/assets/2444081/6b6b7a43-306a-4dc4-aada-0d08d71423ab)

Two issues/questions:

1. What if the user would like to append (instead of replace) the attribution text? So instead of "Leaflet | My attribution text", the user would like to have "Leaflet | Tiles @ Esri - Esri, DeLorme, NAVTEQ, My attribution text" ?
2. Basemaps are also supported in plot mode. So if we keep the default attributions in view mode, to be consistent across modes, we also need a credits in plot mode, whenever `tm_basemap`s are added. Yes or no?

**Comment by olivroy** [comment]
This is great, thanks for implementing! I like the defaults you implemented.

> What if the user would like to append (instead of replace) the attribution text? So instead of "Leaflet | My attribution text", the user would like to have "Leaflet | Tiles @ Esri - Esri, DeLorme, NAVTEQ, My attribution text" ?

I don't have strong feelings, maybe wait for FR and keep it simple for now? Maybe with an `append` argument to `tm_credit()`? 


> Basemaps are also supported in plot mode. So if we keep the default attributions in view mode, to be consistent across modes, we also need a credits in plot mode, whenever tm_basemaps are added. Yes or no?

The original credits are not essential to the map imo, but I wouldn't know the legal / copyright implications. I'd rather not see them by default on static maps with basemaps, but no strong feelings
