### ISSUE TITLE
tm_bubble colour of the legend does not match the colour of the map

### ISSUE THREAD

**Issue by anjelinejeline** [r-tmap/tmap#823]
Hi ,
I need help to make the legend of my map displaying the right colour (gray10)
in the legend as defined in tm_bubble instead of the standard gray ..
Can anyone help ?
```
tm_shape(allpoints) + 
  tm_bubbles(size = "v1", alpha = 0.05, 
             sizes.legend=c(5,15,25,35,45,55), 
             sizes.legend.labels=c("5","15","25","35","45","55"),# vector of labels for that correspond to sizes.legend
             col = "gray10", 
             border.col = "gray10", 
             border.lwd = 0.3, 
             legend.col.show = TRUE,
             title.size = "My points") + 
  tm_layout(legend.outside = TRUE,
            legend.title.size=1.5,
            legend.text.size=1,
            legend.outside.position = "bottom")
```

![image](https://github.com/r-tmap/tmap/assets/145205734/e722da4d-507d-4e1f-bba1-97d9184c5df7)

**Comment by mtennekes** [comment]
Can you create a reproducible example?

This one works:

```r
data(metro)

metro$x = metro$pop2000 / 1e6

tm_shape(metro) + 
	tm_bubbles(size = "x", alpha = 0.05, 
			   sizes.legend=c(5,15,25,35,45,55), 
			   sizes.legend.labels=c("5","15","25","35","45","55"),# vector of labels for that correspond to sizes.legend
			   col = "gray10", 
			   border.col = "gray10", 
			   border.lwd = 0.3, 
			   legend.col.show = TRUE,
			   title.size = "My points") + 
	tm_layout(legend.outside = TRUE,
			  legend.title.size=1.5,
			  legend.text.size=1,
			  legend.outside.position = "bottom")
```

![image](https://github.com/r-tmap/tmap/assets/2444081/15f8751f-0bf2-44b7-b0c1-c51f7e9da13b)

**Comment by anjelinejeline** [comment]
gray10 is supposed to be a dark gray .... 
you can find here attached the dataset I used 
[points.csv](https://github.com/r-tmap/tmap/files/14095624/points.csv)


df_points=read.csv("points.csv")

sf_points=sf::st_as_sf(df_points, coords = c("x","y"),
                    crs="+proj=moll +lon_0=0 +x_0=0 +y_0=0")


```
tm_shape(sf_points) + 
  tm_bubbles(size = "n", alpha = 0.05, 
             sizes.legend=c(1,3,6), 
             sizes.legend.labels=c("1","3","6"),# vector of labels for that correspond to sizes.legend
             col = "gray10", 
             border.col = "gray10", 
             border.lwd = 0.3, 
             legend.col.show = TRUE,
             title.size = "My points") + 
  tm_layout(legend.outside = TRUE,
            legend.title.size=1.5,
            legend.text.size=1,
            legend.outside.position = "bottom")
```

![image](https://github.com/r-tmap/tmap/assets/145205734/5e4bca04-c3c8-472a-b7d8-2d2c004e39f5)

**Comment by mtennekes** [comment]
You've applied an alpha transparency of 0.05, which makes `"gray10"` very light. In the map, the dots appear dark because of the large amount of overlap. The legend doesn't have this overlap, but still applies the same alpha transparency to be consistent with the map. So methodologically, this is correct.

If you want `"gray10"` points in the legend without transparency, you can add a manual legend with `tm_add_legend`:

```{r}
tm_shape(sf_points) + 
	tm_bubbles(size = "n", alpha = .05,
			   size.lim = c(0, 6),
			   legend.size.show = FALSE,
			   col = "gray10", 
			   border.col = "gray10", 
			   border.lwd = 0.3, 
			   legend.col.show = TRUE,
			   title.size = "My points") + 
	tm_layout(legend.outside = TRUE,
			  legend.title.size=1.5,
			  legend.text.size=1,
			  legend.outside.position = "bottom") +
	tm_add_legend(type = "symbol", 
				  size = sqrt(c(1,3,6)/6) * 1.333, 
				  col = "gray10",
				  is.portrait = FALSE,
				  labels = c(1, 3, 6))
```

Please make sure to test the current GitHub version (v4). This example shows both automatic and manual legends:

```{r}
tm_shape(sf_points) + 
	tm_bubbles(size = "n", 
			   fill_alpha = 0.05, 
			   fill = "gray10", 
			   col = "gray10", 
			   lwd = 0.3,
			   size.scale = tm_scale_continuous(ticks = c(1,3,6), limits = c(0, 6)),
			   size.legend = tm_legend("My points", orientation = "landscape")) +
	tm_add_legend(size = sqrt(c(1,3, 6)/6)*1.333, fill = "gray10", col = "gray10", labels = c(1,3, 6), orientation = "landscape", title = "My manual points")
```

![image](https://github.com/r-tmap/tmap/assets/2444081/5bcae9ee-6f69-4434-a457-f33db2639a6f)


The scaling part of `tm_add_legend` is still tricky and requires some insights. By setting the limits manually (in v3 with `size.lim` and in v4 with `limits` in the `tm_scale_continuous` function, you have control of the shown sizes. Symbol sizes correspond to the radius instead of the area, so the square root needs to be taken. Next, these are multiplied by 1.333, because that is the default scale size of bubbles.

**Comment by anjelinejeline** [comment]
@mtennekes thank you so much ... which package are you using? 
I cannot run this code as the function tm_scale_continuous is not found 
```
Error in tm_scale_continuous(ticks = c(1, 3, 6, 9, 12), limits = c(0,  : 
  could not find function "tm_scale_continuous"
```

**Comment by mtennekes** [comment]
@anjelinejeline you need to use the GitHub version (v4) of tmap.
