### ISSUE TITLE
value.neutral for `text`

### ISSUE THREAD

**Issue by Nowosad** [r-tmap/tmap#858]
``` r
library(tmap)
tm_shape(metro) +
  tm_text(text = "name", size = "pop2020")
#> Error in tmapScaleContinuous(x1 = c(5721697, 2835218, 6836849, 15894307, : object 'ids' not found
```

**Comment by mtennekes** [comment]
Fixed, but not too happy with the legend of this map. Why does it show `Hyderabad` and not just `Abc` is something like this?

Currently, `value.neutral` of the visual variable `text` takes some existing value. This can be changed with: 

```r
tm_shape(metro) +
	tm_text(text = "name", size = "pop2020", text.scale = tm_scale_asis(value.neutral = "Abc"))
```

Is this a better alternative for the default settings?

**Comment by mtennekes** [comment]
Agree, but it is not always straightforward to pick existing values. E.g. what to do if there is no text label with the size of a legend item? For this example, the pop2020 values for Lahore, Osaka and Delhi are approx 10, 20, and 30 million, so that would be good candidates.

Maybe for the time being we can settle with `"Abc"`,  but of course the user can change that.

**Comment by mtennekes** [comment]
> Btw. Why "Hyderabad" in this case is used?

Now I know: it takes the most common value. Apparently, there are two 'Hyderabad's: one in India and one in Pakistan, with different coordinates.

**Comment by mtennekes** [comment]
Now changed to the tmap option 'value.neutral', which is for text `"Abc"`. As mentioned earlier, finding values automatically is tricky, as there are always cases in which it doesn't work well.
