### ISSUE TITLE
tm_text fontface not working when using tmap 3.3.4

### ISSUE THREAD

**Issue by arxan11** [r-tmap/tmap#897]
I recently updated the tmap package to version 3.3.4 and I noticed that the `fontface` argument within `tm_text` is not working as it was working before. Unfortunately, I don't remember which tmap version I was using before. When I specify `fontface` within `tm_layout,` it works fine for all map elements except for text labels. I have also used both numerics and text to specify `fontface` e.g. `fontface="bold"` or `fontface=2` with the same result. Can you please advise is this is a bug or whether something might have changed in the updated tmap version?

**Comment by mtennekes** [comment]
With the latest commit it is working again. Don't know when and why it was broken.
Please install the fix with `remotes::install_github("r-tmap/tmap", ref = "v3")`

I won't submit this version anymore to CRAN, because v4 is the next one. 

I would encourage you to test v4 and let me know if all works as expected.

**Comment by arxan11** [comment]
Everything works fine now. Thanks for applying the fix 👍
